name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag official-website-generator:latest

    - name: Save Docker image to tar file
      run: docker save official-website-generator:latest -o official-website-generator.tar

    - name: Upload tar file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: official-website-generator.tar
